--1) SELECT *
-- FROM employee e
-- LEFT JOIN dept d
-- ON e.dept_id = d.dept_id;
--2)Finding employees without a department
-- select e.ename 
-- from employee e 
-- Left Join Dept d 
-- on e.dept_id=d.dept_id
-- where d.dept_id is null;
--3)find dept having no employee
-- select d.dname
-- from dept d 
-- left join employee e 
-- on d.dept_id=e.dept_id
-- where e.eid is null;
--4)number of employees in every department, 
--  including departments with zero employees.
-- select d.dname ,count(e.eid) from dept d  
-- left join employee e 
-- on e.dept_id=d.dept_id
-- group by d.dname;
--5) Display all employees and
-- their department names using LEFT JOIN
-- select e.ename,d.dname 
-- from employee e 
-- left join dept d 
-- on e.dept_id=d.dept_id;
--6)employees who do not belong to any department.
-- select e.ename 
-- from employee e 
-- left join dept d 
-- on e.dept_id=d.dept_id
-- where d.dname is Null;
--7)all departments,the numberof employees in each department,
-- including departments having 0 employees.
-- select d.dname,count(e.eid)
-- from dept d 
-- left join employee e 
-- on e.dept_id=d.dept_id
-- group by d.dname;
--8)Display departments that have no employees.
-- select d.dname 
-- from dept d 
-- left join employee e 
-- on e.dept_id=d.dept_id
-- where e.eid is null;
--9) display Department Name,Total Employees,Average Salary
-- for all departments, including departments with no employees.
-- select d.dname ,count (e.eid),avg(e.Salary)
-- from dept d  
-- left join employee e 
-- on e.dept_id=d.dept_id 
-- group by d.dname;
--10)Display all departments having more than 1 employee, 
--  along with department name and employee count, 
--  sorted by employee count from highest to lowest.
-- select d.dname ,count(e.eid) as Employee_count
-- from dept d 
-- left join employee e 
-- on e.dept_id=d.dept_id 
-- group by d.dname 
-- having count(e.eid)>1
-- order by count(e.eid) desc;
--11)Display all departments along with their total salary,
-- including departments where no employee exists.
-- Show only depts whose total salary is greater than ₹80,000, 
--and sort from highest total salary to lowest.
select d.dname ,sum(salary) as total_salary
from dept d 
left join employee e 
on d.dept_id=e.dept_id 
group by d.dname 
having total_salary>80000
order by total_salary desc;
